---

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: no
  tasks:
    - name: test marathon
      marathon_app:
        args: []
        command: ""
        constraints: []
        cpus: 0.1
        state: present
        name: no-change
        host: http://10.10.7.10:8080
        memory: 128.0
        instances: 1
        container:
          type: DOCKER
          docker:
            image: redis:latest
            network: BRIDGE
            portMappings:
            - containerPort: 6379
              hostPort: 0
              protocol: tcp
            volumes: []
        health_checks: []
        labels: {}
        env: {}
        uris: []
