---

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: no
  tasks:
    - name: test marathon
      marathon_app:
        state: present
        name: simple-app
        host: "http://{{ lookup('env','BEHAVE_IP') }}:8080"
        memory: 128.0
        instances: 1
        container:
          type: DOCKER
          docker:
            image: nginx:latest
            network: BRIDGE
            portMappings:
              - containerPort: 80
                hostPort: 0
                protocol: "tcp"
        env:
          SETTINGS_FLAVOR: local
          SEARCH_BACKEND: sqlalchemy
        health_checks:
          - protocol: HTTP
            path: "/"
            gracePeriodSeconds: 3
            intervalSeconds: 10
            portIndex: 0
            timeoutSeconds: 10
            maxConsecutiveFailures: 3
