# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
# Setup
apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

# Add the repository
echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | \
  tee /etc/apt/sources.list.d/mesosphere.list
echo "deb https://get.docker.com/ubuntu docker main" > /etc/apt/sources.list.d/docker.list
apt-get -y update

apt-get -y install apt-transport-https lxc-docker

apt-get -y install mesos=0.21.1-1.1.ubuntu1404

echo "10.10.7.10" > /etc/mesos-master/ip

echo "docker,mesos" > /etc/mesos-slave/containerizers
echo "5mins" > /etc/mesos-slave/executor_registration_timeout
echo "ERROR" > /etc/mesos-slave/logging_level
echo "10.10.7.10" > /etc/mesos-slave/hostname
echo "10.10.7.10" > /etc/mesos-slave/ip

apt-get -y install marathon=0.8.0-1.1.97.ubuntu1404

mkdir -p /etc/marathon/conf

echo "300000" > /etc/marathon/conf/task_launch_timeout

service zookeeper restart
service mesos-master restart
service mesos-slave restart
service marathon restart

SCRIPT


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "mesos"
  config.vm.network 'private_network', ip: "10.10.7.10"

  config.vm.provision "shell", inline: $script

  config.vm.provider "virtualbox" do |v|
    v.memory = 3072
    v.cpus = 2
  end
end
