---

version: "2"

services:
  zookeeper:
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=127.0.0.1:2888:3888
    image: zookeeper
    network_mode: host
    restart: always

  master:
    environment:
      MESOS_PORT: 5050
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
    image: mesosphere/mesos-master:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    restart: always

  agent:
    command: --work_dir=/tmp
    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker,mesos
    image: mesosphere/mesos-slave:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /sys:/sys
    - /usr/bin/docker:/usr/local/bin/docker

  marathon:
    environment:
      MARATHON_HOSTNAME: 127.0.0.1
      MARATHON_HTTPS_ADDRESS: "${BEHAVE_IP}"
      MARATHON_HTTP_ADDRESS: "${BEHAVE_IP}"
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
      MARATHON_ZK: zk://127.0.0.1:2181/mesos
    image: mesosphere/marathon:v1.3.1
    network_mode: host
    restart: always
